// Async data access functions for generated Miwake data.
//
// These files are generated by scripts in this package:
// - jmdict_eng.json: Full JMDict dictionary (run: deno task download_jmdict)
// - jmdict_furigana.json: Furigana placement data (run: deno task download_jmdictfurigana)
// - jmdict_tags.json: Tag expansions (run: deno task extract_tags)
// - entries/*.json: Individual JMDict entries by ID (run: deno task extract_entries)
// - rarity.sqlite3: Rarity lookup resources (run: deno task build_rarity_resources)

import * as path from "@std/path";
import type { JMdict, JMdictWord } from "@scriptin/jmdict-simplified-types";
import { entriesCache } from "./entries_cache.ts";

export { bccwjLUW2LemmaHit, nwjcSurface1GramHit } from "./rarity_resources.ts";

/** JMDict tag expansions. Key: tag abbreviation, value: full description. */
export type JMDictTags = Record<string, string>;

/** Furigana placement data. Key format: "jmdictId|word|reading", value: Anki furigana format. */
export type JMDictFurigana = Record<string, string>;

/** Map of JMDict entry ID to entry data. */
export type JMDictEntries = Map<string, JMdictWord>;

// Module-level promises for deduplication (the full-dictionary one lives in
// `entries_cache.ts` so the download module can reset it)
let tagsPromise: Promise<JMDictTags> | null = null;
let furiganaPromise: Promise<JMDictFurigana> | null = null;
const preextractedEntryPromises = new Map<string, Promise<JMdictWord>>();

const dataDir = import.meta.dirname!;

/**
 * Lazily loads and returns JMDict tag expansions.
 * Safe to call multiple times concurrently - will deduplicate requests.
 */
export function jmdictTags(): Promise<JMDictTags> {
  if (!tagsPromise) {
    tagsPromise = (async () => {
      const tagsPath = path.join(dataDir, "jmdict_tags.json");
      const content = await Deno.readTextFile(tagsPath);
      return JSON.parse(content) as JMDictTags;
    })();
  }
  return tagsPromise;
}

/**
 * Lazily loads and returns JMDict furigana placement data.
 * Safe to call multiple times concurrently - will deduplicate requests.
 */
export function jmdictFurigana(): Promise<JMDictFurigana> {
  if (!furiganaPromise) {
    furiganaPromise = (async () => {
      const furiganaPath = path.join(dataDir, "jmdict_furigana.json");
      const content = await Deno.readTextFile(furiganaPath);
      return JSON.parse(content) as JMDictFurigana;
    })();
  }
  return furiganaPromise;
}

/**
 * Lazily loads and returns all JMDict entries from the full dictionary.
 * Safe to call multiple times concurrently - will deduplicate requests.
 */
export function allJMDictEntries(): Promise<JMDictEntries> {
  if (!entriesCache.promise) {
    entriesCache.promise = (async () => {
      const jmdictPath = path.join(dataDir, "jmdict_eng.json");
      const content = await Deno.readTextFile(jmdictPath);
      const jmdict = JSON.parse(content) as JMdict;

      const entries: JMDictEntries = new Map();
      for (const word of jmdict.words) {
        entries.set(word.id, word);
      }
      return entries;
    })();
  }
  return entriesCache.promise;
}

/**
 * Lazily loads and returns a single pre-extracted JMDict entry by ID.
 * Safe to call multiple times concurrently - will deduplicate requests.
 * Throws if the entry doesn't exist in the pre-extracted entries.
 */
export function preextractedJMDictEntry(id: string): Promise<JMdictWord> {
  let promise = preextractedEntryPromises.get(id);
  if (!promise) {
    promise = (async () => {
      const entryPath = path.join(dataDir, "entries", `${id}.json`);
      try {
        const content = await Deno.readTextFile(entryPath);
        return JSON.parse(content) as JMdictWord;
      } catch (e) {
        if (e instanceof Deno.errors.NotFound) {
          throw new Error(`JMDict entry ${id} not found in pre-extracted entries`);
        }
        throw e;
      }
    })();
    preextractedEntryPromises.set(id, promise);
  }
  return promise;
}
